/** Declaration file generated by dts-gen */

export function getInfo(name: any, fn: any): any;

export function getLink(name: any, fn: any): any;

export function getList(fn: any): any;

export function getRecommendGoods(fn: any): any;

export function getRecommendMovie(fn: any): any;

export function getRecommends(fn: any): any;

export function getTopics(fn: any): any;

export function search(keyword: any, fn: any): any;

export namespace getInfo {
    const prototype: {
    };

}

export namespace getLink {
    const prototype: {
    };

}

export namespace getList {
    const prototype: {
    };

}

export namespace getRecommendGoods {
    const prototype: {
    };

}

export namespace getRecommendMovie {
    const prototype: {
    };

}

export namespace getRecommends {
    const prototype: {
    };

}

export namespace getTopics {
    const prototype: {
    };

}

export namespace search {
    const prototype: {
    };

}

